---
parser: "@typescript-eslint/parser" # Specifies the ESLint parser
parserOptions:
  ecmaVersion: 2020 # Allows for the parsing of modern ECMAScript features
  sourceType: module # Allows for the use of imports
  ecmaFeatures:
    jsx: true # Allows for the use of imports
plugins:
  - import
  - react-hooks
settings:
  react:
    version: detect # Tells eslint-plugin-react to automatically detect the version of React to use
extends:
  - plugin:react/recommended  # Uses the recommended rules from @eslint-plugin-react
  - plugin:@typescript-eslint/recommended # Uses the recommended rules from @typescript-eslint/eslint-plugin
  - prettier/@typescript-eslint # Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
  - plugin:import/errors # eslint-plugin-import error rules
  - plugin:import/warnings # eslint-plugin-import warning rules
  - plugin:import/typescript # eslint-plugin-import typescript support
  - plugin:import/react # eslint-plugin-import react support
  - plugin:prettier/recommended # Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
rules:
 # Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
  import/order: warn
  prettier/prettier:
  - error
  - endOfLine: auto
