[workspace]
members = [
    "integration-lib",
    "program",
    "program_v2",
]

[profile.release]
opt-level = 3
lto = true
debug = false
strip = "debuginfo"
codegen-units = 1

[profile.test]
opt-level = 2
