/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
export type { IERC3525MetadataDescriptorUpgradeable } from "./IERC3525MetadataDescriptorUpgradeable";
