/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFlagsStorage,
  IFlagsStorageInterface,
} from "../../../contracts/interfaces/IFlagsStorage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "flag",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "index",
        type: "uint8",
      },
    ],
    name: "FlagAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "flag",
        type: "bytes32",
      },
    ],
    name: "FlagRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "prevSuperAdmin",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "superAdmin",
        type: "address",
      },
    ],
    name: "SuperAdminUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_flag",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "_index",
        type: "uint8",
      },
    ],
    name: "addFlag",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_flags",
        type: "bytes32[]",
      },
      {
        internalType: "uint8[]",
        name: "_indexes",
        type: "uint8[]",
      },
    ],
    name: "addFlags",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "flagIndexes",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_flag",
        type: "bytes32",
      },
    ],
    name: "isFlagSupported",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_flag",
        type: "bytes32",
      },
    ],
    name: "removeFlag",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_flags",
        type: "bytes32[]",
      },
    ],
    name: "removeFlags",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "superAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "supportedFlagsMask",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newSuperAdmin",
        type: "address",
      },
    ],
    name: "updateSuperAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFlagsStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IFlagsStorageInterface {
    return new utils.Interface(_abi) as IFlagsStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlagsStorage {
    return new Contract(address, _abi, signerOrProvider) as IFlagsStorage;
  }
}
