{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::146055947386:policy/solana-ociv-usage
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.name") }}
  name: {{ $job.serviceAccount.name }}
  {{- else }}
  name: {{ $job.name }}
  {{- end }}
  labels:
    app: {{ $release_name }}
    cron: {{ $job.name }}
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.annotations") }}
  {{- with $job.serviceAccount.annotations }}
#  annotations:
#    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
