name: "NPM Auto Publish"

on:
  push:
    branches:
      - main
      - develop

    paths:
      - "solana/program_v2/packages/client/cli/package.json"
      - "solana/program_v2/packages/client/core/package.json"
      - "solana/program_v2/packages/client/idl/package.json"

jobs:
  publish-gateway-solana-idl:
    uses: "./.github/workflows/npm-auto-publish-workflow.yml"
    with:
      environment: "npm-auto-publish"
      production-branch: "main"
      root-directory: "solana/program_v2"
      package-path: "solana/program_v2/packages/client/idl/package.json"
    secrets:
      publish-token: ${{ secrets.NPM_TOKEN }}

  publish-gateway-solana-client:
    needs: publish-gateway-solana-idl
    uses: "./.github/workflows/npm-auto-publish-workflow.yml"
    with:
      environment: "npm-auto-publish"
      production-branch: "main"
      root-directory: "solana/program_v2"
      package-path: "solana/program_v2/packages/client/core/package.json"
    secrets:
      publish-token: ${{ secrets.NPM_TOKEN }}

  publish-gateway-solana-cli:
    needs: publish-gateway-solana-client
    uses: "./.github/workflows/npm-auto-publish-workflow.yml"
    with:
      environment: "npm-auto-publish"
      production-branch: "main"
      root-directory: "solana/program_v2"
      package-path: "solana/program_v2/packages/client/cli/package.json"
    secrets:
      publish-token: ${{ secrets.NPM_TOKEN }}