name: Solana Gateway Program Build
on:
  push:
    paths:
      - 'solana/program/**'
  pull_request:
jobs:
  solana-gateway-program-build-test:
    name: Build, lint and test the solana gateway program on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['15.x']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./solana/program

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Use Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: Cache build dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./program/target
          key: cargo-test-${{ hashFiles('Cargo.lock') }}

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          
      - name: Run functional tests
        uses: actions-rs/cargo@v1
        with:
          command: test-bpf

# TODO
#      - name: Run linter
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
        
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build-bpf
