name: Main
on:
  pull_request:
jobs:
  solana-gateway-ts-build:
    name: Build, lint the solana-gateway-ts library on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['15.x']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./solana/gatekeeper-ts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: yarn-solana-gateway-ts-${{ hashFiles('yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  solana-gateway-ts-unit_tests:
    name: Test the solana-gateway-ts library with dependencies stubbed out

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['15.x']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./solana/gatekeeper-ts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: yarn-solana-gateway-ts-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Unit tests
        run: yarn test:unit

